version: '3.8'

services:
  pvsolar-scheduler:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: pvsolar-scheduler
    restart: unless-stopped
    ports:
      - "8009:8009"
    volumes:
      - ../config:/app/config:ro
    environment:
      - PVSOLAR_SCHEDULER_DEBUG=false
      - API_PORT=8009
    networks:
      - pvsolar-net

networks:
  pvsolar-net:
    driver: bridge
